import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  Check,
  CheckCircle2,
  Circle,
  ExternalLink,
  Flag,
  Loader2,
  RefreshCw,
  Route,
  Sparkles,
  Target
} from "lucide-react";
import { cn } from "~/lib/cn";
import type { GoalPath, PathMilestone } from "~/shared/schema";
import { Button } from "../components/ui/Button";
import {
  GENERATION_JOBS_KEY,
  isActiveGenerationJob,
  showQueuedFeedback,
  showQueueError
} from "../lib/use-generation-feedback";

const STALE_GENERATION_MS = 10 * 60 * 1000;

type Props = { goalId: string; onBack: () => void };

export function PathDetail({ goalId, onBack }: Props) {
  const queryClient = useQueryClient();
  const [evidence, setEvidence] = useState("");
  const goalsQuery = useQuery({
    queryKey: ["goals"],
    queryFn: () => window.komorebi.goals.list()
  });
  const pathQuery = useQuery({
    queryKey: ["path", goalId],
    queryFn: () => window.komorebi.paths.get(goalId)
  });
  const generationJobsQuery = useQuery({
    queryKey: GENERATION_JOBS_KEY,
    queryFn: () => window.komorebi.generation.recentJobs(20)
  });
  const pathJobActive = (generationJobsQuery.data ?? []).some(
    (job) =>
      job.kind === "path-generate" &&
      job.targetId === goalId &&
      isActiveGenerationJob(job)
  );

  const refresh = () =>
    Promise.all([
      queryClient.invalidateQueries({ queryKey: ["path", goalId] }),
      queryClient.invalidateQueries({ queryKey: ["checklist", "today"] })
    ]);

  const generate = useMutation({
    mutationFn: () =>
      window.komorebi.generation.enqueuePathGeneration({
        requestId: crypto.randomUUID(),
        goalId
      }),
    onSuccess: showQueuedFeedback,
    onError: showQueueError
  });
  const autoGenerated = useRef(false);
  useEffect(() => {
    if (
      autoGenerated.current ||
      pathQuery.isLoading ||
      pathQuery.data ||
      generate.isPending ||
      pathJobActive
    ) return;
    autoGenerated.current = true;
    generate.mutate();
  }, [pathQuery.isLoading, pathQuery.data, generate, pathJobActive]);

  const activate = useMutation({
    mutationFn: () =>
      window.komorebi.paths.activate({
        pathId: pathQuery.data!.id,
        expectedRevision: pathQuery.data!.revision
      }),
    onSettled: refresh
  });
  const current = pathQuery.data?.milestones.find((milestone) => milestone.status === "current");
  const complete = useMutation({
    mutationFn: () =>
      window.komorebi.paths.completeMilestone({
        pathId: pathQuery.data!.id,
        milestoneId: current!.id,
        evidence,
        expectedRevision: pathQuery.data!.revision
      }),
    onSuccess: () => setEvidence(""),
    onSettled: refresh
  });

  const path = pathQuery.data;
  const goal = goalsQuery.data?.find((candidate) => candidate.id === goalId);
  const mutationError = generate.error || activate.error || complete.error;
  const generationLooksInterrupted =
    path?.status === "generating" &&
    Date.now() - Date.parse(path.updatedAt) >= STALE_GENERATION_MS;
  const ready = path && ["draft", "active", "completed", "superseded"].includes(path.status);

  return (
    <div className="mx-auto max-w-4xl px-5 pb-28 pt-10 md:px-12 md:pb-24 md:pt-14">
      <button
        onClick={onBack}
        className="pressable -ml-2 inline-flex items-center gap-2 rounded-md px-2 py-1.5 text-sm text-[var(--color-ink-2)] hover:bg-[var(--color-panel)] hover:text-[var(--color-ink)]"
      >
        <ArrowLeft className="h-3.5 w-3.5" strokeWidth={1.75} />
        Goals
      </button>

      <header className="mt-10">
        <div className="flex flex-wrap items-center gap-x-3 gap-y-2 text-[var(--color-ink-2)]">
          <span className="inline-flex items-center gap-2 font-mono text-2xs uppercase tracking-[0.2em]">
            <Route className="h-3.5 w-3.5" strokeWidth={1.75} />
            Your path
          </span>
          {path && <PathStatus path={path} />}
        </div>
        <h1 className="mt-4 max-w-3xl text-4xl font-semibold text-[var(--color-ink)] md:text-[38px] md:leading-[1.12]">
          {goal?.title ?? "Your destination"}
        </h1>
        {goal?.description && (
          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-[var(--color-ink-2)]">
            {goal.description}
          </p>
        )}
      </header>

      {pathQuery.isLoading && <PathSkeleton />}
      {!pathQuery.isLoading && !path && (
        <ResearchState
          pending={generate.isPending || pathJobActive}
          onGenerate={() => generate.mutate()}
        />
      )}
      {path?.status === "generating" && (
        <ResearchState
          pending={!generationLooksInterrupted}
          interrupted={generationLooksInterrupted}
          onGenerate={() => generate.mutate()}
        />
      )}
      {path?.status === "failed" && (
        <section className="mt-14 border-t border-[var(--color-rule)] pt-9">
          <RefreshCw className="h-5 w-5 text-[var(--color-danger)]" strokeWidth={1.5} />
          <h2 className="mt-4 text-2xl font-semibold">The research pass didn’t finish.</h2>
          <p className="mt-3 max-w-xl text-base leading-relaxed text-[var(--color-ink-2)]">
            {path.error || "Something interrupted path research. Your destination is safe."}
          </p>
          <Button
            className="mt-6"
            onClick={() => generate.mutate()}
            disabled={generate.isPending || pathJobActive}
          >
            {generate.isPending || pathJobActive ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
            Research again
          </Button>
        </section>
      )}

      {ready && (
        <>
          {path.status === "draft" && (
            <section className="mt-12 flex flex-col gap-5 border-y border-[var(--color-rule)] py-6 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <h2 className="text-lg font-semibold text-[var(--color-ink)]">Ready for your review</h2>
                <p className="mt-1 max-w-xl text-sm leading-relaxed text-[var(--color-ink-2)]">
                  Activating this route makes its first milestone the source of your daily actions.
                </p>
              </div>
              <Button size="lg" className="shrink-0" onClick={() => activate.mutate()} disabled={activate.isPending}>
                {activate.isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Flag className="h-3.5 w-3.5" />}
                Activate path
              </Button>
            </section>
          )}

          <section className={cn("grid gap-10", path.status === "draft" ? "mt-12" : "mt-14", "md:grid-cols-[minmax(0,1.55fr)_minmax(220px,0.75fr)]")}>
            <div>
              <Kicker>Research brief</Kicker>
              <p className="mt-4 text-xl leading-relaxed text-[var(--color-ink)]">
                {path.researchSummary}
              </p>
            </div>
            <aside className="md:border-l md:border-[var(--color-rule)] md:pl-8">
              <Kicker>Assumptions</Kicker>
              <p className="mt-4 text-sm leading-relaxed text-[var(--color-ink-2)]">
                {path.assumptions}
              </p>
            </aside>
          </section>

          <section className="mt-16">
            <div className="flex items-end justify-between gap-4 border-b border-[var(--color-rule)] pb-4">
              <div>
                <Kicker>The route</Kicker>
                <h2 className="mt-2 text-2xl font-semibold text-[var(--color-ink)]">Milestones</h2>
              </div>
              <span className="pb-1 font-mono text-xs text-[var(--color-ink-2)]">
                {completedCount(path)} of {path.milestones.length} complete
              </span>
            </div>
            <ol>
              {path.milestones.map((milestone, index) => (
                <MilestoneRow key={milestone.id} milestone={milestone} index={index} />
              ))}
            </ol>
          </section>

          {path.status === "active" && current && (
            <section className="mt-10 border-y border-[var(--color-rule)] py-9">
              <div className="grid gap-7 md:grid-cols-[minmax(0,0.85fr)_minmax(320px,1.15fr)] md:items-start">
                <div>
                  <Kicker accent>Advance the path</Kicker>
                  <h2 className="mt-3 text-xl font-semibold text-[var(--color-ink)]">
                    Complete “{current.title}”
                  </h2>
                  <p className="mt-2 text-sm leading-relaxed text-[var(--color-ink-2)]">
                    Daily actions build toward this outcome. Record concrete evidence only when the
                    milestone itself is met.
                  </p>
                </div>
                <div>
                  <label className="text-sm font-medium text-[var(--color-ink)]" htmlFor="milestone-evidence">
                    Evidence of completion
                  </label>
                  <textarea
                    id="milestone-evidence"
                    className="input mt-2 min-h-28 resize-y"
                    rows={4}
                    value={evidence}
                    placeholder="Link the shipped work, describe the result, or note who reviewed it…"
                    onChange={(event) => setEvidence(event.target.value)}
                  />
                  <div className="mt-3 flex justify-end">
                    <Button disabled={!evidence.trim() || complete.isPending} onClick={() => complete.mutate()}>
                      {complete.isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5" />}
                      Complete milestone
                    </Button>
                  </div>
                </div>
              </div>
            </section>
          )}

          <Sources path={path} />
        </>
      )}

      {mutationError && (
        <p className="mt-6 border-l-2 border-[var(--color-danger)] pl-4 text-sm text-[var(--color-danger)]">
          {(mutationError as Error).message}
        </p>
      )}
    </div>
  );
}

function PathStatus({ path }: { path: GoalPath }) {
  const labels: Record<GoalPath["status"], string> = {
    generating: "Researching",
    draft: "Draft for review",
    active: "Active",
    failed: "Needs attention",
    superseded: "Previous version",
    completed: "Completed"
  };
  return (
    <span className="inline-flex items-center gap-2 font-mono text-2xs uppercase tracking-[0.16em]">
      <span
        className={cn(
          "h-1.5 w-1.5 rounded-full bg-[var(--color-rule-2)]",
          path.status === "active" && "bg-[var(--color-accent)]",
          path.status === "completed" && "bg-[var(--color-leaf)]",
          path.status === "failed" && "bg-[var(--color-danger)]"
        )}
      />
      Version {path.version} · {labels[path.status]}
    </span>
  );
}

function ResearchState({ pending, interrupted = false, onGenerate }: { pending: boolean; interrupted?: boolean; onGenerate: () => void }) {
  return (
    <section className="mt-14 max-w-2xl border-t border-[var(--color-rule)] pt-10">
      <div className="flex h-9 w-9 items-center justify-center rounded-full bg-[var(--color-panel)] text-[var(--color-accent-strong)]">
        {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
      </div>
      <h2 className="mt-5 text-2xl font-semibold text-[var(--color-ink)]">
        {pending ? "Researching the route" : interrupted ? "Research was interrupted" : "Turn this destination into a path"}
      </h2>
      <p className="mt-3 max-w-xl text-base leading-relaxed text-[var(--color-ink-2)]">
        {pending
          ? "Komorebi is checking current, authoritative sources and shaping them into outcomes you can review."
          : interrupted
            ? "The previous pass took longer than expected. Restart it without losing your destination."
            : "Komorebi will research current expectations and propose a short route of evidence-based milestones."}
      </p>
      {!pending && (
        <Button size="lg" className="mt-6" onClick={onGenerate}>
          <Sparkles className="h-3.5 w-3.5" />
          {interrupted ? "Retry research" : "Research my path"}
        </Button>
      )}
      {pending && (
        <div className="mt-8 h-px overflow-hidden bg-[var(--color-rule)]">
          <div className="h-full w-1/3 bg-[var(--color-accent)]" style={{ animation: "path-research 1.8s ease-in-out infinite" }} />
        </div>
      )}
    </section>
  );
}

function MilestoneRow({ milestone, index }: { milestone: PathMilestone; index: number }) {
  const completed = milestone.status === "completed";
  const current = milestone.status === "current";
  const Icon = completed ? CheckCircle2 : current ? Target : Circle;
  return (
    <li className="grid grid-cols-[30px_minmax(0,1fr)] gap-4 border-b border-[var(--color-rule)] py-8 sm:grid-cols-[36px_minmax(0,1fr)] sm:gap-5">
      <div
        className={cn(
          "mt-0.5 flex h-7 w-7 items-center justify-center rounded-full text-[var(--color-ink-3)] sm:h-8 sm:w-8",
          current && "bg-[var(--color-accent)] text-white",
          completed && "text-[var(--color-ink)]"
        )}
      >
        <Icon className="h-4 w-4" strokeWidth={current ? 2 : 1.6} />
      </div>
      <div>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <span className="font-mono text-2xs uppercase tracking-[0.18em] text-[var(--color-ink-2)]">Milestone {index + 1}</span>
          <span className={cn("font-mono text-2xs uppercase tracking-[0.14em] text-[var(--color-ink-2)]", current && "text-[var(--color-accent-strong)]")}>
            {current ? "Current focus" : milestone.status}
          </span>
        </div>
        <h3 className="mt-2 text-xl font-semibold text-[var(--color-ink)]">{milestone.title}</h3>
        <p className="mt-2 text-base leading-relaxed text-[var(--color-ink)]">{milestone.outcome}</p>
        <div className="mt-5 grid gap-5 sm:grid-cols-2">
          <div>
            <Kicker>Why this matters</Kicker>
            <p className="mt-2 text-sm leading-relaxed text-[var(--color-ink-2)]">{milestone.rationale}</p>
          </div>
          <div>
            <Kicker>Complete when</Kicker>
            <p className="mt-2 text-sm leading-relaxed text-[var(--color-ink-2)]">{milestone.completionCriteria}</p>
          </div>
        </div>
        {milestone.completionEvidence && (
          <p className="mt-5 border-l-2 border-[var(--color-leaf)] pl-3 text-sm text-[var(--color-ink-2)]">
            <b className="font-medium text-[var(--color-ink)]">Evidence:</b> {milestone.completionEvidence}
          </p>
        )}
      </div>
    </li>
  );
}

function Sources({ path }: { path: GoalPath }) {
  if (path.sources.length === 0) return null;
  return (
    <section className="mt-14">
      <div className="flex items-end justify-between gap-3 border-b border-[var(--color-rule)] pb-4">
        <div>
          <Kicker>Grounding</Kicker>
          <h2 className="mt-2 text-xl font-semibold text-[var(--color-ink)]">Sources</h2>
        </div>
        {path.researchAt && <span className="pb-0.5 font-mono text-xs text-[var(--color-ink-2)]">Researched {new Date(path.researchAt).toLocaleDateString()}</span>}
      </div>
      <ul>
        {path.sources.map((source) => (
          <li key={source.id} className="border-b border-[var(--color-rule)]">
            <a href={source.url} target="_blank" rel="noreferrer" className="group flex items-center justify-between gap-4 py-4">
              <div className="min-w-0">
                <div className="font-medium text-[var(--color-ink)] group-hover:text-[var(--color-accent-strong)]">{source.title}</div>
                <div className="mt-1 truncate font-mono text-xs text-[var(--color-ink-2)]">{sourceHost(source.url)}</div>
              </div>
              <ExternalLink className="h-3.5 w-3.5 shrink-0 text-[var(--color-ink-3)]" strokeWidth={1.75} />
            </a>
          </li>
        ))}
      </ul>
    </section>
  );
}

function Kicker({ children, accent = false }: { children: React.ReactNode; accent?: boolean }) {
  return <div className={cn("font-mono text-2xs uppercase tracking-[0.19em] text-[var(--color-ink-2)]", accent && "text-[var(--color-accent-strong)]")}>{children}</div>;
}

function PathSkeleton() {
  return (
    <div className="mt-14 space-y-9 animate-pulse">
      <div className="h-px bg-[var(--color-rule)]" />
      <div className="h-6 w-2/3 rounded bg-[var(--color-panel)]" />
      <div className="h-40 border-y border-[var(--color-rule)]" />
    </div>
  );
}

function completedCount(path: GoalPath): number {
  return path.milestones.filter((milestone) => milestone.status === "completed").length;
}

function sourceHost(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}
