import { generateSuggestion, type HistoryItem } from "../claude/generate";
import { buildContextBlocks } from "../context/registry";
import { getUserId, listConnections } from "../integrations/composio";
import { deleteGoal, getGoal, listActiveGoals } from "../store/goals";
import {
  deleteReflectionsForSuggestions,
  listReflectionsForSuggestion
} from "../store/reflections";
import {
  deleteSuggestionsForGoal,
  getSuggestion,
  insertSuggestion,
  listRecentSuggestionsForGoal,
  listSuggestionsForDate,
  updateSuggestionStatus
} from "../store/suggestions";
import type { Suggestion } from "~/shared/types";

/** YYYY-MM-DD in the user's local timezone. */
export function localDate(d: Date = new Date()): string {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export type ChecklistDay = {
  date: string;
  items: Suggestion[];
  hasGoals: boolean;
};

export async function getTodayChecklist(): Promise<ChecklistDay> {
  const date = localDate();
  const [items, goals] = await Promise.all([
    listSuggestionsForDate(date),
    listActiveGoals()
  ]);
  return { date, items, hasGoals: goals.length > 0 };
}

/**
 * Generate one suggestion for each active goal for today.
 * Skips goals that already have a suggestion today (idempotent).
 * Returns the full checklist for today (including any pre-existing items).
 */
export async function generateTodayChecklist(): Promise<ChecklistDay> {
  const date = localDate();
  const [activeGoals, existing] = await Promise.all([
    listActiveGoals(),
    listSuggestionsForDate(date)
  ]);

  if (activeGoals.length === 0) {
    return { date, items: existing, hasGoals: false };
  }

  // Goals are "covered" only if they have a non-skipped suggestion today.
  // Skipped ones leave the goal free to be re-generated by Top up.
  const alreadyCovered = new Set(
    existing.filter((s) => s.status !== "skipped").map((s) => s.goalId)
  );
  const goalsToGenerate = activeGoals.filter((g) => !alreadyCovered.has(g.id));

  if (goalsToGenerate.length === 0) {
    return { date, items: existing, hasGoals: true };
  }

  // Context is fetched once per generation pass, shared across goals.
  let contextBlocks: Awaited<ReturnType<typeof buildContextBlocks>> = [];
  try {
    const userId = getUserId();
    const connections = await listConnections(userId);
    contextBlocks = await buildContextBlocks({ userId, connections });
  } catch (err) {
    console.error("[orchestrator] context fetch failed (proceeding without):", err);
  }

  const newSuggestions = await Promise.all(
    goalsToGenerate.map(async (goal) => {
      const recent = await listRecentSuggestionsForGoal(goal.id, 14);
      const history: HistoryItem[] = await Promise.all(
        recent.map(async (s) => ({
          suggestion: s,
          reflections: await listReflectionsForSuggestion(s.id)
        }))
      );
      const draft = await generateSuggestion({
        goal,
        history,
        date,
        contextBlocks
      });
      return insertSuggestion({ goalId: goal.id, date, draft });
    })
  );

  return {
    date,
    items: [...existing, ...newSuggestions].sort((a, b) =>
      a.createdAt.localeCompare(b.createdAt)
    ),
    hasGoals: true
  };
}

/**
 * Delete a goal and everything it owns (suggestions + their reflections).
 * Order matters: collect IDs first, then delete leaves before the trunk.
 */
export async function deleteGoalCascade(goalId: string): Promise<void> {
  const removedSuggestionIds = await deleteSuggestionsForGoal(goalId);
  await deleteReflectionsForSuggestions(removedSuggestionIds);
  await deleteGoal(goalId);
}

/**
 * Mark a suggestion as skipped, then generate a fresh suggestion for the same
 * goal using current history + context. Returns the new suggestion.
 */
export async function skipAndRegenerate(suggestionId: string): Promise<Suggestion> {
  const original = await getSuggestion(suggestionId);
  if (!original) throw new Error(`Suggestion not found: ${suggestionId}`);

  await updateSuggestionStatus(suggestionId, "skipped");

  const goal = await getGoal(original.goalId);
  if (!goal) throw new Error(`Goal not found: ${original.goalId}`);

  let contextBlocks: Awaited<ReturnType<typeof buildContextBlocks>> = [];
  try {
    const userId = getUserId();
    const connections = await listConnections(userId);
    contextBlocks = await buildContextBlocks({ userId, connections });
  } catch (err) {
    console.error("[orchestrator] context fetch failed (proceeding without):", err);
  }

  const recent = await listRecentSuggestionsForGoal(goal.id, 14);
  const history: HistoryItem[] = await Promise.all(
    recent.map(async (s) => ({
      suggestion: s,
      reflections: await listReflectionsForSuggestion(s.id)
    }))
  );

  const date = localDate();
  const draft = await generateSuggestion({ goal, history, date, contextBlocks });
  return insertSuggestion({ goalId: goal.id, date, draft });
}
